piwww: testrun - add proposal routes.
lukebp/politeia pull request #49
Opened 2020-10-09 22:17 UTC by amassarwi

2020-10-11 17:51 UTC, amassarwi commented on politeiawww/cmd/piwww/testrun.go
> +// testPropsWithComments tests the propsal & comments routes
```suggestion
// testPropsWithComments tests the propsal routes
```

Will do in comment routes PR.

2020-10-11 19:04 UTC, amassarwi commented on politeiawww/cmd/piwww/testrun.go
> +	fmt.Printf("  New proposal\n")
This was wrapped in a standalone func on #50, as we submit a new proposal and then use it to run comment routes.

2020-10-12 16:08 UTC, lukebp requested changes
These need to be more comprehensive.  Make sure to test the common unvetted and vetted paths.

Submit new proposal
Edit unvetted proposal
Censor unvetted proposal
Submit new proposal
Make proposal public
Edit vetted proposal
Censor vetted proposal
Submit new proposal
Make proposal public
Abandon vetted proposal
Submit new proposal and leave it unvetted
Get proposal inventory
Get unvetted proposals
Get vetted proposals

2020-10-13 14:09 UTC, lukebp requested changes
This PR needs some work.  Go through the cms testrun code and look at how things are setup.  That's what I want for this code too.  Also, a general comment is that your functions are too specific.  Functions should do only 1 thing and should be generic functions that map to the data model.  See my comments for more details.

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +	minPasswordLength int
Why do you need to use globals here?

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func createUserAndVerifyEmail(minPasswordLength int, resendEmail bool) (*testUser, error) {
This function is doing way too many things.  A function should only do one thing.  You're using it to do multiple things: create a new user, test the verification resend route, and test the update user key route.  Do not do this.  If you create a function to create a new user then it should not be testing additional routes in it.

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func submitNewProposal(verify bool) (string, error) {
You don't need a bool for `verify`.  The client should always be verifying the returned response.

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func proposalPublic(token string) error {
This is too specific of a function.  You should have a `proposalSetStatus` function that allows you to set the status to whatever you want so you don't need a new function for every status.

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func proposalEdit(token string, unvetted, random bool) error {
What's the purpose of `random`?  If its set to false this function is going to error.  It has to be true, so why do you need it as an argument?

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func proposalEdit(token string, unvetted, random bool) error {
I would prefer this to be:
```suggestion
func proposalEdit(state pi.PropStateT, token string) error {
```

For two reasons:
1. Listing the state first is how the data model is setup.  Specify the state (which corresponds to a db on the backend) then specify the token (which corresponds to a db entry in that db).
2. Using `pi.PropStateT` makes the function call more descriptive: `proposalEdit(pi.PropStateUnvetted, token)` vs `proposalsEdit(true, token)`

2020-10-13 14:09 UTC, lukebp commented on politeiawww/cmd/piwww/testrun.go
> +func proposals(ps pi.Proposals) error {
Why do you have a function that fetches proposals, but that doesn't return the proposals that it fetched?  That doesn't make any sense.

2020-10-13 14:22 UTC, amass01 commented on politeiawww/cmd/piwww/testrun.go
> +	minPasswordLength int
I thought it's better than passing them around also to nested functions.

2020-10-13 14:27 UTC, amass01 commented on politeiawww/cmd/piwww/testrun.go
> +func proposalEdit(token string, unvetted, random bool) error {
Totally agree

2020-10-13 15:08 UTC, amassarwi commented on politeiawww/cmd/piwww/testrun.go
> +func proposalPublic(token string) error {
It's just a wrapper, i have already `proposalSetStatus` but also added proposalPublic, proposalCensor & proposalAbandon as wrappers.

2020-10-14 11:40 UTC, amassarwi commented on politeiawww/cmd/piwww/testrun.go
> +// This function returns with user logged out
```suggestion
// This function returns with the user logged out
```

2020-10-14 11:41 UTC, amassarwi commented on politeiawww/cmd/piwww/testrun.go
> +// This function returns with user logged out
updated this in #50

2020-10-20 14:28 UTC, lukebp requested changes
The testrun command should fetch data using both the full sized token and the short token.  This should be applied to proposals, comments, and votes.  Anytime it fetches data from the pi api.

2020-11-02 16:36 UTC, lukebp approved these changes
ACK

2020-11-02 16:36 UTC, merged